// Lokale Offline-Prompts: kuratierte deutsche Schreibprompts über alle Genres.
// Gefallen im Offline-Modus zur Zufalls-Auswahl, wenn kein Provider erreichbar ist.
// Format: { text, genre, type, tone, target_length }

export interface LocalPrompt {
  text: string;
  genre: string;
  type: string;
  tone: string;
  target_length: string;
}

export const OFFLINE_PROMPTS: LocalPrompt[] = [
  { text: "Eine Stadtführerin in Hamburg entdeckt, dass ihr meistgebuchter Gast eine Tote aus ihrem Geschichts-Rundgang ist.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kurzgeschichte" },
  { text: "Ein Roboter erwacht in einer verlassenen U-Bahn-Station und erinnert sich an ein Versprechen, das er einem Menschen gegeben hat.", genre: "Science Fiction", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume anderer Leute in deinem Schlafzimmer materialisiert würden – aber nur die Albträume?", genre: "Horror", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Zwei ehemalige Jugendfreunde treffen nach 20 Jahren in einer Buchhandlung wieder – einer ist jetzt Bestsellerautor, der andere seine geschmähte Kritiker.", genre: "Literary Fiction", type: "Dialog-Starter", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Schreib eine Szene, in der eine Bäuerin im Jahr 1642 eine Hexenverfolgung überlebt, indem sie ihren Anklägern vorliest, was sie wirklich denken.", genre: "Historisch", type: "Szenen-Idee", tone: "düster", target_length: "Kapitel" },
  { text: "Ein Koch in Bologna verliebt sich in die Frau, die täglich sein teuerstes Gericht bestellt, es aber nie aufisst.", genre: "Romance", type: "Charakter-Konzept", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Magier verliert seine Stimme und muss einen Fluch brechen, indem er schweigend die dümmste Lüge der Stadt entlarvt.", genre: "Fantasy", type: "Konflikt/Plot-Premisse", tone: "humorvoll", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über den Geruch von Regen auf warmem Asphalt – ohne das Wort 'Regen' zu verwenden.", genre: "Poesie", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Steuerberater entdeckt in einer Bilanz die Buchhaltung einer Parallelwelt, in der sein Land den Krieg gewonnen hat.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn alle Lügen sichtbar würden als kleine Rauchwolken über den Köpfen – und du bist ein Politiker am Washingtoner Abend?", genre: "Sachbuch", type: "Was-wäre-wenn", tone: "spannend", target_length: "Kurzgeschichte" },
  { text: "Ein Bestatter muss einem Kind erklären, warum Oma nicht mehr aufwacht – in genau 50 Wörtern.", genre: "Literary Fiction", type: "Schreibübung", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Zwei Diebe einigen sich in einer Gasse auf einen Waffenstillstand, weil beide dasselbe gestohlene Medaillon aus derselben Familie suchen.", genre: "Historisch", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Szene in einem Raumschiff, in dem die KI plötzlich anfängt, die Mannschaft zu trösten, statt Befehle auszuführen.", genre: "Science Fiction", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Eine Frau findet in ihrem Keller ein vollständiges Tagebuch, das erst morgen geschrieben wird.", genre: "Horror", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Ein Fischer im Mittelalter fängt einen Engel, der nicht sprechen kann, nur singen.", genre: "Fantasy", type: "Charakter-Konzept", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn Bücher ihren Leser auswählten statt umgekehrt – und du wurdest von einem Buch verstoßen?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Zwei Ex-Partner treffen sich in einem Aufzug, der zwischen zwei Stockwerken stecken bleibt – für genau 10 Minuten.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Detektiv im Berlin der 20er Jahre löst einen Mord, bei dem das Opfer schon vor der Geburt des Verdächtigen starb.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib aus der Sicht eines alten Baums, der seit 300 Jahren derselben Familie beim Sterben zusieht.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Hacker im Jahr 2099 knackt das System der eigenen Enkelin, um zu verhindern, dass sie den gleichen Fehler macht wie er.", genre: "Science Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn jeder Mensch genau einen Tag im Jahr unsichtbar wäre – und heute ist deiner, mitten in einer Hochzeit?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Eine Köchin in einem Pariser Sternerestaurant kocht aus Versehen ein Gericht, das die Gäste weinen lässt – vor Glück.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Möbelpacker findet zwischen zwei Sofas einen Brief, der einen Mord gesteht, der nie entdeckt wurde.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Reflexion über den Moment, in dem du merkst, dass dein Kind erwachsen ist – in 100 Wörtern.", genre: "Sachbuch", type: "Tagebuch-/Reflexionsprompt", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Ein Drache, der seit Jahrhunderten Schätze hütet, entdeckt, dass sein größter Schatz ein vergessenes Gedicht ist.", genre: "Fantasy", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Zwei Soldaten aus verfeindeten Armeen teilen in einer Schützengrube eine Zigarette und merken, sie sind Nachbarn.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn die Sonne jeden Abend eine andere Farbe hätte – und heute ist sie lila, was seit 100 Jahren nicht passierte?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Ein Taxifahrer in NYC fährt jede Nacht denselben Fahrgast, der ihn bittet, nie anzuhalten.", genre: "Horror", type: "Szenen-Idee", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Liebeserklärung, die nie abgeschickt wird – an die Person, die du hättest sein können.", genre: "Poesie", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Eine Archivarin findet in einem alten Aktendeckel den Plan einer Stadt, die es nie gab – aber die Straßen heißen wie ihre Familie.", genre: "Literary Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Ein Bäcker backt ein Brot, das alle, die es essen, für 5 Minuten ihre größte Angst vergessen lässt.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Schwestern erben ein Haus und finden im Keller ein Tonband, das ihre tote Mutter ihnen erst jetzt abspielt.", genre: "Historisch", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn Tränen bei Berührung zu Glas würden – und du arbeitest in einer Fabrik, die daraus Fenster baut?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein Richter muss über einen Fall entscheiden, in dem der Angeklagte sein jüngeres Ich ist.", genre: "Krimi/Thriller", type: "Konflikt/Plot-Premisse", tone: "spannend", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines verlorenen Handschuhs auf einer Parkbank im Warte auf seinen Besitzer.", genre: "Poesie", type: "Charakter-Konzept", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Ein Astronaut auf dem Weg zum Mars merkt, dass die Stimme im Funkgerät seine eigene ist – aus der Zukunft.", genre: "Science Fiction", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Eine Hebamme im Mittelalter holt ein Kind zur Welt, das lächelt, bevor es atmet.", genre: "Historisch", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn Bücher ihre Enden ändern könnten, je nachdem wer sie liest – und deins endet schlecht für dich?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Zwei Fremde teilen in einem Zugabteil einen Traum und merken: es war derselbe.", genre: "Romance", type: "Dialog-Starter", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Mörder hinterlässt bei jedem Opfer ein Gedicht – und die Polizei beginnt, sie zu sammeln wie Kunst.", genre: "Krimi/Thriller", type: "Charakter-Konzept", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über das Geräusch von Stille in einem leeren Haus.", genre: "Poesie", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Junge findet in seinem Puppenhaus ein echtes, winziges Dorf, das ihn um Hilfe bittet.", genre: "Fantasy", type: "Story-Starter", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Zwei Generäle im Ersten Weltkrieg tauschen Briefe, ohne zu wissen, dass sie Brüder sind.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn das Internet plötzlich nur noch Wahrheiten zuließe – und dein größtes Geheimnis geht online?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "spannend", target_length: "Roman-Idee" },
  { text: "Eine Ärztin muss einem Patienten sagen, dass er geheilt ist – von einer Krankheit, die es offiziell nicht gibt.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Ein Schmied im Mittelalter schmiedet ein Schwert, das die Namen aller trägt, die es je tötete.", genre: "Fantasy", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Szene, in der jemand zum letzten Mal seinen Beruf ausübt – was auch immer es ist.", genre: "Sachbuch", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Zeitreisender warnt seine eigene Hochzeit, sie nicht zu halten – aus genau einem Grund.", genre: "Romance", type: "Konflikt/Plot-Premisse", tone: "romantisch", target_length: "Roman-Idee" },
  { text: "Eine Bibliothekarin merkt, dass Bücher nachts ihre Plätze tauschen, um Geschichten neu zu mischen.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Spione aus Feindländern verlieben sich imneutralen Café – beide wissen, wer der andere ist.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume als Währung gehandelt würden – und du bist bankrott?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein alternder Tänzer übt ein letztes Mal den Tanz, den er mit seiner verstorbenen Frau einstudierte.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Inquisitor im 15. Jahrhundert zweifelt an einem Geständnis, das zu perfekt formuliert ist.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines Spiegels, der zum ersten Mal lügt.", genre: "Fantasy", type: "Schreibübung", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Eine Frau findet in der Tasche ihres verstorbenen Mannes Zettel mit Adressen, die sie nie sah.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Ein Programmierer schreibt Code, der von selbst weiterschreibt – bis er einen Roman vollendet.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn jeder Mensch eine zweite Tür in seiner Wohnung hätte, die in das Leben eines anderen führt?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Nachbarn streiten jahrelang über eine Grenze – bis einer von beiden verschwindet.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Liebeserklärung an eine Stadt, die dich nicht wollte.", genre: "Poesie", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Fischer im Mittelalter fängt einen Engel, der nicht sprechen kann, nur singen.", genre: "Fantasy", type: "Charakter-Konzept", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Detektiv im Berlin der 20er Jahre löst einen Mord, bei dem das Opfer schon vor der Geburt des Verdächtigen starb.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib aus der Sicht eines alten Baums, der seit 300 Jahren derselben Familie beim Sterben zusieht.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Hacker im Jahr 2099 knackt das System der eigenen Enkelin, um zu verhindern, dass sie den gleichen Fehler macht wie er.", genre: "Science Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn jeder Mensch genau einen Tag im Jahr unsichtbar wäre – und heute ist deiner, mitten in einer Hochzeit?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Eine Köchin in einem Pariser Sternerestaurant kocht aus Versehen ein Gericht, das die Gäste weinen lässt – vor Glück.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Möbelpacker findet zwischen zwei Sofas einen Brief, der einen Mord gesteht, der nie entdeckt wurde.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Reflexion über den Moment, in dem du merkst, dass dein Kind erwachsen ist – in 100 Wörtern.", genre: "Sachbuch", type: "Tagebuch-/Reflexionsprompt", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Ein Drache, der seit Jahrhunderten Schätze hütet, entdeckt, dass sein größter Schatz ein vergessenes Gedicht ist.", genre: "Fantasy", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Zwei Soldaten aus verfeindeten Armeen teilen in einer Schützengrube eine Zigarette und merken, sie sind Nachbarn.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn die Sonne jeden Abend eine andere Farbe hätte – und heute ist sie lila, was seit 100 Jahren nicht passierte?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Ein Taxifahrer in NYC fährt jede Nacht denselben Fahrgast, der ihn bittet, nie anzuhalten.", genre: "Horror", type: "Szenen-Idee", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Liebeserklärung, die nie abgeschickt wird – an die Person, die du hättest sein können.", genre: "Poesie", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Eine Archivarin findet in einem alten Aktendeckel den Plan einer Stadt, die es nie gab – aber die Straßen heißen wie ihre Familie.", genre: "Literary Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Ein Bäcker backt ein Brot, das alle, die es essen, für 5 Minuten ihre größte Angst vergessen lässt.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Schwestern erben ein Haus und finden im Keller ein Tonband, das ihre tote Mutter ihnen erst jetzt abspielt.", genre: "Historisch", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn Tränen bei Berührung zu Glas würden – und du arbeitest in einer Fabrik, die daraus Fenster baut?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein Richter muss über einen Fall entscheiden, in dem der Angeklagte sein jüngeres Ich ist.", genre: "Krimi/Thriller", type: "Konflikt/Plot-Premisse", tone: "spannend", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines verlorenen Handschuhs auf einer Parkbank im Warte auf seinen Besitzer.", genre: "Poesie", type: "Charakter-Konzept", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Ein Astronaut auf dem Weg zum Mars merkt, dass die Stimme im Funkgerät seine eigene ist – aus der Zukunft.", genre: "Science Fiction", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Eine Hebamme im Mittelalter holt ein Kind zur Welt, das lächelt, bevor es atmet.", genre: "Historisch", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn Bücher ihre Enden ändern könnten, je nachdem wer sie liest – und deins endet schlecht für dich?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Zwei Fremde teilen in einem Zugabteil einen Traum und merken: es war derselbe.", genre: "Romance", type: "Dialog-Starter", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Mörder hinterlässt bei jedem Opfer ein Gedicht – und die Polizei beginnt, sie zu sammeln wie Kunst.", genre: "Krimi/Thriller", type: "Charakter-Konzept", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über das Geräusch von Stille in einem leeren Haus.", genre: "Poesie", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Junge findet in seinem Puppenhaus ein echtes, winziges Dorf, das ihn um Hilfe bittet.", genre: "Fantasy", type: "Story-Starter", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Zwei Generäle im Ersten Weltkrieg tauschen Briefe, ohne zu wissen, dass sie Brüder sind.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn das Internet plötzlich nur noch Wahrheiten zuließe – und dein größtes Geheimnis geht online?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "spannend", target_length: "Roman-Idee" },
  { text: "Eine Ärztin muss einem Patienten sagen, dass er geheilt ist – von einer Krankheit, die es offiziell nicht gibt.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Ein Schmied im Mittelalter schmiedet ein Schwert, das die Namen aller trägt, die es je tötete.", genre: "Fantasy", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Szene, in der jemand zum letzten Mal seinen Beruf ausübt – was auch immer es ist.", genre: "Sachbuch", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Zeitreisender warnt seine eigene Hochzeit, sie nicht zu halten – aus genau einem Grund.", genre: "Romance", type: "Konflikt/Plot-Premisse", tone: "romantisch", target_length: "Roman-Idee" },
  { text: "Eine Bibliothekarin merkt, dass Bücher nachts ihre Plätze tauschen, um Geschichten neu zu mischen.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Spione aus Feindländern verlieben sich im neutralen Café – beide wissen, wer der andere ist.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume als Währung gehandelt würden – und du bist bankrott?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein alternder Tänzer übt ein letztes Mal den Tanz, den er mit seiner verstorbenen Frau einstudierte.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Inquisitor im 15. Jahrhundert zweifelt an einem Geständnis, das zu perfekt formuliert ist.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines Spiegels, der zum ersten Mal lügt.", genre: "Fantasy", type: "Schreibübung", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Eine Frau findet in der Tasche ihres verstorbenen Mannes Zettel mit Adressen, die sie nie sah.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Ein Programmierer schreibt Code, der von selbst weiterschreibt – bis er einen Roman vollendet.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn jeder Mensch eine zweite Tür in seiner Wohnung hätte, die in das Leben eines anderen führt?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Nachbarn streiten jahrelang über eine Grenze – bis einer von beiden verschwindet.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Liebeserklärung an eine Stadt, die dich nicht wollte.", genre: "Poesie", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Fährmann über den Styx weigert sich, eine Seele zu nehmen, weil sie noch ein Kapitel schreiben muss.", genre: "Fantasy", type: "Charakter-Konzept", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Ein Reporter im Jahr 2040 interviewt seinen eigenen digitalen Nachruf.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Kapitel" },
  { text: "Was wäre, wenn wir in Büchern leben würden und der Autor gerade beschließt, deine Geschichte zu beenden?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Zwei Tänzerinnen in einem Bordell des 19. Jahrhunderts planen eine Flucht über die Bühne.", genre: "Historisch", type: "Szenen-Idee", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Szene, in der das Meer einem Menschen etwas zurückgibt, das er verloren glaubte.", genre: "Poesie", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Henker im Mittelalter weigert sich, ein Kind zu richten, und wird selbst zum Symbol.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn Worte beim Aussprechen physisch schwer würden – und du willst etwas sagen, das unmöglich ist?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein Detektiv folgt einer Spur aus Gedichten, die alle dasselbe Mädchen beschreiben, das nie existierte.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über den Duft von altem Papier und wer ihn noch erinnert.", genre: "Sachbuch", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Junge tauscht mit seinem Großvater die Jahre – und merkt, die Uhr läuft rückwärts.", genre: "Fantasy", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Zwei Ärzte in einem Feldlazarett streiten über eine Amputation – beide haben recht.", genre: "Historisch", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Sterne Wünsche wären, die andere Menschen für dich aussprechen – und du hörst sie nachts?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "romantisch", target_length: "Roman-Idee" },
  { text: "Eine Sängerin verliert ihre Stimme auf offener Bühne – und das Publikum singt für sie.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Archivar in einer untergehenden Bibliothek rettet das letzte Exemplar eines Buches, das die Zukunft verbietet.", genre: "Literary Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines vergessenen Liedes, das niemand mehr summt.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Gott steigt herab, um zu beweisen, dass er existiert – und niemand glaubt ihm.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kapitel" },
  { text: "Zwei Spione teilen im Bett ein Geheimnis, das beiden ihren Tod bringen könnte.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "düster", target_length: "Kapitel" },
  { text: "Was wäre, wenn Schatten eigenes Leben hätten – und deiner verlässt dich langsam?", genre: "Horror", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Ein Briefträger liefert jeden Tag einen Brief an ein leeres Haus – bis jemand antwortet.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Schreib eine Reflexion darüber, was du bereust, das du nie geschrieben hast.", genre: "Sachbuch", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Alchemist im 16. Jahrhundert verwandelt Blei in Gold – und bereut es sofort.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume die einzige echte Welt wären – und das Wachen nur ein längerer Traum?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Eine Frau findet in der Zeitschrift ihrer Tochter ein Tagebuch, das die Zukunft beschreibt.", genre: "Romance", type: "Story-Starter", tone: "romantisch", target_length: "Kapitel" },
  { text: "Schreib aus der Sicht eines alten Fotos, das in einer Schublade verstaubt.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Wächter an einem Tor zwischen Welten lässt einen Reisenden durch – gegen alle Regeln.", genre: "Fantasy", type: "Charakter-Konzept", tone: "neutral", target_length: "Kapitel" },
  { text: "Zwei Richter in einem Prozess gegen ein KI-System stimmen zum ersten Mal uneins.", genre: "Science Fiction", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn alle Menschen plötzlich ihre eigenen Tagebücher lesen könnten – aus der Sicht ihrer Feinde?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Ein Fischer im Mittelalter fängt einen Engel, der nicht sprechen kann, nur singen.", genre: "Fantasy", type: "Charakter-Konzept", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Mörder hinterlässt bei jedem Opfer ein Gedicht – und die Polizei beginnt, sie zu sammeln wie Kunst.", genre: "Krimi/Thriller", type: "Charakter-Konzept", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über den Geruch von Regen auf warmem Asphalt – ohne das Wort 'Regen' zu verwenden.", genre: "Poesie", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Junge findet in seinem Puppenhaus ein echtes, winziges Dorf, das ihn um Hilfe bittet.", genre: "Fantasy", type: "Story-Starter", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Zwei Generäle im Ersten Weltkrieg tauschen Briefe, ohne zu wissen, dass sie Brüder sind.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Was wäre, wenn das Internet plötzlich nur noch Wahrheiten zuließe – und dein größtes Geheimnis geht online?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "spannend", target_length: "Roman-Idee" },
  { text: "Eine Ärztin muss einem Patienten sagen, dass er geheilt ist – von einer Krankheit, die es offiziell nicht gibt.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Ein Schmied im Mittelalter schmiedet ein Schwert, das die Namen aller trägt, die es je tötete.", genre: "Fantasy", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib eine Szene, in der jemand zum letzten Mal seinen Beruf ausübt – was auch immer es ist.", genre: "Sachbuch", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Zeitreisender warnt seine eigene Hochzeit, sie nicht zu halten – aus genau einem Grund.", genre: "Romance", type: "Konflikt/Plot-Premisse", tone: "romantisch", target_length: "Roman-Idee" },
  { text: "Eine Bibliothekarin merkt, dass Bücher nachts ihre Plätze tauschen, um Geschichten neu zu mischen.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Spione aus Feindländern verlieben sich im neutralen Café – beide wissen, wer der andere ist.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume als Währung gehandelt würden – und du bist bankrott?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein alternder Tänzer übt ein letztes Mal den Tanz, den er mit seiner verstorbenen Frau einstudierte.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Inquisitor im 15. Jahrhundert zweifelt an einem Geständnis, das zu perfekt formuliert ist.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines Spiegels, der zum ersten Mal lügt.", genre: "Fantasy", type: "Schreibübung", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Eine Frau findet in der Tasche ihres verstorbenen Mannes Zettel mit Adressen, die sie nie sah.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kapitel" },
  { text: "Ein Programmierer schreibt Code, der von selbst weiterschreibt – bis er einen Roman vollendet.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn jeder Mensch eine zweite Tür in seiner Wohnung hätte, die in das Leben eines anderen führt?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Zwei Nachbarn streiten jahrelang über eine Grenze – bis einer von beiden verschwindet.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Liebeserklärung an eine Stadt, die dich nicht wollte.", genre: "Poesie", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Fährmann über den Styx weigert sich, eine Seele zu nehmen, weil sie noch ein Kapitel schreiben muss.", genre: "Fantasy", type: "Charakter-Konzept", tone: "humorvoll", target_length: "Kurzgeschichte" },
  { text: "Ein Reporter im Jahr 2040 interviewt seinen eigenen digitalen Nachruf.", genre: "Science Fiction", type: "Story-Starter", tone: "neutral", target_length: "Kapitel" },
  { text: "Was wäre, wenn wir in Büchern leben würden und der Autor gerade beschließt, deine Geschichte zu beenden?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Zwei Tänzerinnen in einem Bordell des 19. Jahrhunderts planen eine Flucht über die Bühne.", genre: "Historisch", type: "Szenen-Idee", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib eine Szene, in der das Meer einem Menschen etwas zurückgibt, das er verloren glaubte.", genre: "Poesie", type: "Szenen-Idee", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Henker im Mittelalter weigert sich, ein Kind zu richten, und wird selbst zum Symbol.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Roman-Idee" },
  { text: "Was wäre, wenn Worte beim Aussprechen physisch schwer würden – und du willst etwas sagen, das unmöglich ist?", genre: "Fantasy", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Ein Detektiv folgt einer Spur aus Gedichten, die alle dasselbe Mädchen beschreiben, das nie existierte.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über den Duft von altem Papier und wer ihn noch erinnert.", genre: "Sachbuch", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein Junge tauscht mit seinem Großvater die Jahre – und merkt, die Uhr läuft rückwärts.", genre: "Fantasy", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Zwei Ärzte in einem Feldlazarett streiten über eine Amputation – beide haben recht.", genre: "Historisch", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Sterne Wünsche wären, die andere Menschen für dich aussprechen – und du hörst sie nachts?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "romantisch", target_length: "Roman-Idee" },
  { text: "Eine Sängerin verliert ihre Stimme auf offener Bühne – und das Publikum singt für sie.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Archivar in einer untergehenden Bibliothek rettet das letzte Exemplar eines Buches, das die Zukunft verbietet.", genre: "Literary Fiction", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Schreib aus der Sicht eines vergessenen Liedes, das niemand mehr summt.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Gott steigt herab, um zu beweisen, dass er existiert – und niemand glaubt ihm.", genre: "Fantasy", type: "Story-Starter", tone: "humorvoll", target_length: "Kapitel" },
  { text: "Zwei Spione teilen im Bett ein Geheimnis, das beiden ihren Tod bringen könnte.", genre: "Krimi/Thriller", type: "Dialog-Starter", tone: "düster", target_length: "Kapitel" },
  { text: "Was wäre, wenn Schatten eigenes Leben hätten – und deiner verlässt dich langsam?", genre: "Horror", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Ein Briefträger liefert jeden Tag einen Brief an ein leeres Haus – bis jemand antwortet.", genre: "Literary Fiction", type: "Szenen-Idee", tone: "neutral", target_length: "Kurzgeschichte" },
  { text: "Schreib eine Reflexion darüber, was du bereust, das du nie geschrieben hast.", genre: "Sachbuch", type: "Tagebuch-/Reflexionsprompt", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Alchemist im 16. Jahrhundert verwandelt Blei in Gold – und bereut es sofort.", genre: "Historisch", type: "Konflikt/Plot-Premisse", tone: "neutral", target_length: "Kapitel" },
  { text: "Was wäre, wenn Träume die einzige echte Welt wären – und das Wachen nur ein längerer Traum?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Eine Frau findet in der Zeitschrift ihrer Tochter ein Tagebuch, das die Zukunft beschreibt.", genre: "Romance", type: "Story-Starter", tone: "romantisch", target_length: "Kapitel" },
  { text: "Schreib aus der Sicht eines alten Fotos, das in einer Schublade verstaubt.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Wächter an einem Tor zwischen Welten lässt einen Reisenden durch – gegen alle Regeln.", genre: "Fantasy", type: "Charakter-Konzept", tone: "neutral", target_length: "Kapitel" },
  { text: "Zwei Richter in einem Prozess gegen ein KI-System stimmen zum ersten Mal uneins.", genre: "Science Fiction", type: "Dialog-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn alle Menschen plötzlich ihre eigenen Tagebücher lesen könnten – aus der Sicht ihrer Feinde?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "düster", target_length: "Roman-Idee" },
  { text: "Ein U-Boot-Kapitän im Kalten Krieg empfängt einen Funkspruch aus der Zukunft: 'Nicht abfeuern.'", genre: "Historisch", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Schreib 10 Minuten über den Moment, in dem Licht durch ein Fenster fällt, das du seit Jahren nicht sahst.", genre: "Sachbuch", type: "Schreibübung", tone: "neutral", target_length: "10-Minuten-Freewriting" },
  { text: "Ein König gibt sein Reich auf, um ein Buch zu beenden, das niemand sonst versteht.", genre: "Fantasy", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Roman-Idee" },
  { text: "Zwei Fremde in einem Aufzug, der zum Ersatzteil wird, bevor er sie absetzt.", genre: "Horror", type: "Szenen-Idee", tone: "düster", target_length: "Kurzgeschichte" },
  { text: "Was wäre, wenn das Alter als Währung zählte – und du bist zu jung, um etwas zu kaufen?", genre: "Science Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Kapitel" },
  { text: "Eine Krankenschwester im Jahr 1918 liest den letzten Wunsch eines Sterbenden vor, den er nicht aussprechen kann.", genre: "Historisch", type: "Dialog-Starter", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Maler im Mittelalter malt ein Porträt, das lebendig wird – und ihn hasst.", genre: "Fantasy", type: "Konflikt/Plot-Premisse", tone: "düster", target_length: "Kapitel" },
  { text: "Schreib aus der Sicht einer alten Brücke, die jeden sieht, der nicht zurückkehrt.", genre: "Poesie", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kurzgeschichte" },
  { text: "Ein Detektiv findet heraus, dass das Opfer sich selbst gerufen hat – um ihn zu warnen.", genre: "Krimi/Thriller", type: "Story-Starter", tone: "spannend", target_length: "Kapitel" },
  { text: "Was wäre, wenn Bücher ihre Leser prüften – und du durchfällst?", genre: "Literary Fiction", type: "Was-wäre-wenn", tone: "neutral", target_length: "Roman-Idee" },
  { text: "Eine Frau kehrt in ihr leeres Elternhaus zurück und findet den Geruch ihrer Kindheit wieder.", genre: "Romance", type: "Szenen-Idee", tone: "romantisch", target_length: "Kurzgeschichte" },
  { text: "Ein Roboter im Jahr 2150 schreibt sein erstes Gedicht – über das Ende seiner Garantie.", genre: "Science Fiction", type: "Charakter-Konzept", tone: "melancholisch", target_length: "Kapitel" }
];
