// Editor-Modi für den Modus-Switcher.
export type EditorMode =
  | "editor"
  | "prompts"
  | "knowledge"
  | "diagnostics"
  | "preflight"
  | "snapshots"
  | "kdp"
  | "publishing"
  | "fragments"
  | "voices"
  | "map"
  | "dialogue"
  | "versions"
  | "obstruction"
  | "dream"
  | "imagegen"
  | "covergen"
  | "blurbgen"
  | "scientificwriting"
  | "timeline"
  | "characters"
  | "worldbuilding"
  | "research"
  | "investigate";
